version: 2
jobs:
  build:
    docker:
      - image: viacard/veritools:latest
    steps:
      - checkout:
      - setup_remote_docker: 
          docker_layer_caching: true 
      - run:
          command: |
            make testall
            


